services:
  - type: web
    name: inventory-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: PORT
        value: 3000

  - type: static
    name: inventory-frontend
    buildCommand: npm install && npx ng build --configuration=production
    publishDir: dist
    rootDir: frontend
    envVars:
      - key: NG_CLI_ANALYTICS
        value: false
